/*
**  Class:          PQDIF.Validator.RecObservation
**  Description:	One of these collections per channel
**
** --------------------------------------------------------------------------
**
** Copyright 2025 PQDIF Authors
**
** Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
**
**      http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
** either express or implied. See the License for the specific language governing permissions and limitations under the License.
**
** See the LICENSE file distributed with this work for copyright and licensing information, the AUTHORS file for a list of
** copyright holders, and the CONTRIBUTORS file for the list of contributors.
**
** SPDX - License - Identifier: Apache - 2.0
*/


namespace PQDIF.Validator
{
    // Contains fundamental classes and base classes that define commonly-used value and reference data types, events and event handlers, interfaces, attributes, and processing exceptions.
    using System;

    // Contains interfaces and classes that define generic collections
    using System.Collections.Generic;

    // Defines IEEE PQDIF data types including PQDIF timestamps
    using PQDIFNet;

    // Defines IEEE PQDIF IDs
    using static PQDIFNet.Constants.Logical;

    // For logging errors, warnings, other messages.
    using PQDIF.Log;

    /// <summary>
    /// Record-level tag which identifies an observation an event, measurement, etc.
    /// </summary>
    public class RecObservation
    {

        /// <summary>
        /// Name of the Observation
        /// </summary>
        /// <remarks>Required</remarks>
        public string ObservationName = "";

        /// <summary>
        /// Time this observation was created
        /// </summary>
        /// <remarks>Required</remarks>
        public DateTime TimeCreate = new DateTime();

        /// <summary>
        /// The start time of the observation
        /// </summary>
        /// <remarks>Required</remarks>
        public DateTime TimeStart = new DateTime();

        /// <summary>
        /// Type of trigger which caused the observation
        /// </summary>
        public uint TriggerMethodID = (uint)ID_TRIGGER_METH_NONE;

        /// <summary>
        /// Time this observation was triggered if appropriate
        /// </summary>
        public DateTime? TimeTriggered = null;

        /// <summary>
        /// Index into tagChannelInstances collection within this record. This specifies which channel(s) initiated the observation.
        /// </summary>
        public uint[] ChannelTriggerIdx = null;

        /// <summary>
        /// The serial number of the observation (if generated by an instrument, for example)
        /// </summary>
        public uint? ObservationSerial = null;

        /// <summary>
        /// Serial number (for example, a specific cycle), which can be used to correlate observations
        /// </summary>
        public uint? ObservationAggregationSerial = null;

        /// <summary>
        /// IEEE 1159 Disturbance Categories
        /// </summary>
        public Guid DisturbanceCategoryID = new Guid();

        /// <summary>
        /// This collection contains a set of channel instances. It is not required to contain the same number of channels as there are channel instances
        /// This can be determined on an observation-by-observation basis.
        /// </summary>
        /// <remarks>Required</remarks>
        public List<OneChannelInst> ChannelInstances = new List<OneChannelInst>();

        /// <summary>
        /// Arbitrary comments
        /// </summary>
        public string Comments = "";

        /// <summary>
        /// Direction of disturbance represented by the data in this observation.  Value of 0 means unknown, 1 means originated from load side, 2 means originated from source side.
        /// </summary>
        public uint? CharactDisturbDirection = null;

        /// <summary>
        /// Quality of the direction result given in another tag.  Range is from 0 (no confidence), to 100 (full confidence)
        /// </summary>
        public uint? CharactDisturbDirectionQuality = null;

        /// <summary>
        /// Minimum RMS Voltage Magnitude (per unit)
        /// </summary>
        public double? CharactMinVoltagePU = null;

        /// <summary>
        /// Maximum RMS Voltage Magnitude (per unit)
        /// </summary>
        public double? CharactMaxVoltagePU = null;

        /// <summary>
        /// Minimum RMS Voltage Magnitude (volts)
        /// </summary>
        public double? CharactMinVoltage = null;

        /// <summary>
        /// Maximum RMS Voltage Magnitude (volts)
        /// </summary>
        public double? CharactMaxVoltage = null;

        /// <summary>
        /// Minimum RMS Current Magnitude (amps)
        /// </summary>
        public double? CharactMinCurrent = null;

        /// <summary>
        /// Maximum RMS Current Magnitude (amps)
        /// </summary>
        public double? CharactMaxCurrent = null;

        /// <summary>
        /// Simple characterization value: duration of disturbance (seconds)
        /// </summary>
        public double? CharactDuration;

        /// <summary>
        /// An ID used to classify a voltage sag by the impact on voltage magnitude and phase angle
        /// </summary>
        public Guid SagTypeID = new Guid();

        /// <summary>
        /// Specifies the number of seconds to add to tag values and/or series values that store TIMESTAMP types in a Data Source, 
        /// Monitor Settings, or Observation record from Local Standard Time (LST) to Local Time. If <see cref="LSTtoLocal"/> is used 
        /// without tagUTCtoLST, then tagUTCtoLST shall be 0.
        /// </summary>
        public double? LSTtoLocal = null;

        /// <summary>
        /// IEEE Std 1159.3 Compliance Logger for this <see cref="RecObservation"/>
        /// </summary>
        /// <remarks>Not an IEEE 1159.3 Tag</remarks>
        public Logger LoggerCompliance = new Logger();

        /// <summary>
        /// Application Logger for this <see cref="RecObservation"/>
        /// </summary>
        /// <remarks>Not an IEEE 1159.3 Tag</remarks>
        public Logger LoggerApplication = new Logger();

        /// <summary>
        /// Initializes a new instance of the <see cref="RecObservation"/> class.
        /// </summary>
        public RecObservation()
        {
            // Default Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecDataSource"/> class.
        /// </summary>
        /// <param name="PqdifFile">PQDIF file from which to read a container record</param>
        /// <param name="PointerRecObservation">Pointer a Data Source Record in <paramref name="PqdifFile"/></param>
        /// <param name="LogLevelApplication">Specifies the Log Level for Application Errors</param>
        /// <param name="LogLevelCompliance">Specifies the Log Level for Compliance Errors</param>
        /// <param name="RecordOK"><c>true</c> if the record was read OK</param>
        public RecObservation(CPQDIFNet PqdifFile, ref IntPtr PointerRecObservation, LogLevels LogLevelApplication, LogLevels LogLevelCompliance, out bool RecordOK)
        {
            // Initialize the return value
            RecordOK = true;

            // Set up an error handler
            try
            {
                // Set the logger level
                LoggerApplication.LogLevel = LogLevelApplication;
                LoggerCompliance.LogLevel = LogLevelCompliance;

                // Initialize flags that tell us if required tags are missing                
                bool MissingObservationName = true;
                bool MissingTimeCreate = true;
                bool MissingTimeStart = true;
                bool MissingTriggerMethodID = true;
                bool MissingChannelInstances = true;                

                // Determine the number of tags associated with the current record
                int CollectionCount = 0;
                bool Result = PqdifFile.CollectionGetCount(PointerRecObservation, ref CollectionCount);
                if (!Result)
                {
                    LoggerApplication.Log("CollectionGetCount", LogLevels.Error);
                    RecordOK = false;
                    return;
                }


                // For each tag in the observation...
                for (int CollectionIndex = 0; CollectionIndex < CollectionCount; CollectionIndex++)
                {
                    // Create a log message for this collection index.
                    string CollectionLogMessagePrefix = "Collection Index " + CollectionIndex.ToString();

                    // Get the pointer to the current tag
                    IntPtr PointerCollectionTag = new IntPtr();
                    Result = PqdifFile.CollectionGetEntry(PointerRecObservation, CollectionIndex, ref PointerCollectionTag);
                    if (!Result)
                    {
                        LoggerApplication.Log(CollectionLogMessagePrefix + "CollectionGetEntry", LogLevels.Error);
                        RecordOK = false;
                        return;
                    }

                    // Get the tag ID and tag name
                    Guid TagID = new Guid();
                    string TagName = "";
                    Result = PqdifFile.ElementGetTag(PointerCollectionTag, ref TagID, ref TagName);
                    if (!Result)
                    {
                        LoggerApplication.Log(CollectionLogMessagePrefix + ": ElementGetTag", LogLevels.Error);
                        RecordOK = false;
                        return;
                    }

                    // Initialize a flag that tells us that the current TagID was not matched to a known TagID.
                    bool TagMatched = false;

                    // Try to match the tag to tagObservationName
                    if (!TagMatched)
                    { 
                        TagMatched = PQDIFNetWrapper.ElementGetString(TagID, tagObservationName, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref ObservationName);
                        if (TagMatched)
                            MissingObservationName = false;
                    }

                    // Try to match the tag to tagTimeCreate
                    if (!TagMatched)
                    { 
                        TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagTimeCreate, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref TimeCreate);
                        if (TagMatched)
                            MissingTimeCreate = false;
                    }

                    // Try to match the tag to tagTimeStart
                    if (!TagMatched)
                    {
                        TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagTimeStart, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref TimeStart);
                        if (TagMatched)
                            MissingTimeStart = false;
                    }

                    // Try to match the tag to tagTriggerMethodID
                    if (!TagMatched)
                    {
                        TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagTriggerMethodID, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref TriggerMethodID);
                        if (TagMatched)
                            MissingTriggerMethodID = false;
                    }

                    // Try to match the tag to other optional tags
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagTimeTriggered, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref TimeTriggered);
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetVectorArray(TagID, tagChannelTriggerIdx, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref ChannelTriggerIdx);
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagObservationSerial, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref ObservationSerial);
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagObservationAggregationSerial, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref ObservationAggregationSerial);
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagDisturbanceCategoryID, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref DisturbanceCategoryID);
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetString(TagID, tagComments, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref Comments);
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagCharactMinVoltagePU, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref CharactMinVoltagePU);
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagCharactMaxVoltagePU, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref CharactMaxVoltagePU);
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagCharactMinVoltage, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref CharactMinVoltage);
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagCharactMaxVoltage, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref CharactMaxVoltage);
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagCharactMinCurrent, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref CharactMinCurrent);
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagCharactMaxCurrent, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref CharactMaxCurrent);
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagSagTypeID, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref SagTypeID);
                    if (!TagMatched) TagMatched = PQDIFNetWrapper.ElementGetScalarData(TagID, tagLSTtoLocal, PqdifFile, PointerCollectionTag, LoggerApplication, LoggerCompliance, CollectionLogMessagePrefix, ref LSTtoLocal);

                    // If this tag is for a Channel Instances collection...
                    if (TagID == tagChannelInstances)
                    {

                        // We matched the tag.
                        TagMatched = true;

                        // We have found the required channel instances collection
                        MissingChannelInstances = false;

                        // Copy the channel instances pointer
                        IntPtr ChannelInstancesPointer = PointerCollectionTag;

                        // Determine if ChannelInstancesPointer points to a collection and the count of elements associated with that collection.
                        int ChannelInstCount = PQDIFNetWrapper.CollectionGetCount(PqdifFile, ChannelInstancesPointer, LoggerApplication, LoggerCompliance);

                        // Log a a compliance error if the channel instance collection does not have at least one channel instance.
                        if (ChannelInstCount == 0)
                            LoggerCompliance.Log(CollectionLogMessagePrefix + ": tagChannelInstances must have at least one tagOneChannelInst Record.", LogLevels.Error);

                        // For each channel instance...
                        for (int ChannelInstanceIndex = 0; ChannelInstanceIndex < ChannelInstCount; ChannelInstanceIndex++)
                        {
                            // Create a log message for this channel instance.
                            string ChannelInstanceLogMessagePrefix = CollectionLogMessagePrefix + ": Channel Instance Index " + ChannelInstanceIndex.ToString();

                            // Get the pointer to the current channel instance
                            IntPtr ThisChannelInstPointer = new IntPtr();
                            Result = PqdifFile.CollectionGetEntry(ChannelInstancesPointer, ChannelInstanceIndex, ref ThisChannelInstPointer);

                            // If we could get a pointer to the current channel intance...
                            if (Result)
                            {
                                // Create the current channel instance record.
                                OneChannelInst ThisChannelInst = new OneChannelInst(PqdifFile, ThisChannelInstPointer, LoggerApplication.LogLevel, LoggerCompliance.LogLevel, out RecordOK);

                                // If we created the channel instance, then add it to the list of channel instances.
                                if (RecordOK)
                                    ChannelInstances.Add(ThisChannelInst);
                            }
                            else
                            {
                                LoggerApplication.Log(ChannelInstanceLogMessagePrefix + ": CollectionGetEntry Error", LogLevels.Error);
                            }

                        } // For each channel instance

                    } // If this tag is for a Channel Instances collection

                    // If still not matched, try to match the current tag to tagBlank, which can be used to leave a space in a collection.
                    if (!TagMatched)
                        TagMatched = TagID == tagBlank;

                    // If the TagID has not been matched, then log an information message about this unknown tag.
                    if (!TagMatched)
                        LoggerCompliance.Log(CollectionLogMessagePrefix + ": Unknown or Unexpected Tag: " + PQDIFNetWrapper.GetName(TagID), LogLevels.Info);

                } // For each tag in the data source


                // Log warnings if required tags are missing.
                if (MissingObservationName)
                    LoggerCompliance.Log("Required tagObservationName is Missing.", LogLevels.Error);
                if (MissingTimeCreate)
                    LoggerCompliance.Log("Required tagTimeCreate is Missing.", LogLevels.Error);
                if (MissingTimeStart)
                    LoggerCompliance.Log("Required tagTimeStart is Missing.", LogLevels.Error);
                if (MissingTriggerMethodID)
                    LoggerCompliance.Log("Required tagTriggerMethodID is Missing.", LogLevels.Error);
                if (MissingChannelInstances)
                    LoggerCompliance.Log("Required tagChannelInstances is Missing.", LogLevels.Error);


            } // try

            // Handle exceptions here.
            catch (Exception ex)
            {
                LoggerApplication.Log(ex.Message, LogLevels.Error);
            }

        } // RecObservation


        /// <summary>
        /// Returns the <see cref="RecObservation" /> Collection Formated in XML
        /// </summary>
        /// <param name="ApplicationLog">If set to <c>true</c>, application log messages will be returned</param>
        /// <param name="ComplianceLog">If set to <c>true</c>, IEEE Std 1159.3 compliance log messages will be returned</param>
        /// <param name="MaxSeriesValues">Maximum Count of Series Samples to Export to XML</param>
        /// <returns>Data Source Record Formated in XML</returns>
        public string GetXML(bool ApplicationLog, bool ComplianceLog, uint? MaxSeriesValues)
        {
            // Initialize a string builder
            System.Text.StringBuilder StringBuilder = new System.Text.StringBuilder();
            StringBuilder.Append("<tagRecObservation>\r\n");

            // If we should return application logs...
            if (ApplicationLog)
            {
                StringBuilder.Append("<ApplicationLog>\r\n");
                StringBuilder.Append(LoggerApplication.GetLogXML());
                StringBuilder.Append("</ApplicationLog>\r\n");
            }

            // If we should return compliance logs...
            if (ComplianceLog)
            {
                StringBuilder.Append("<ComplianceLog>\r\n");
                StringBuilder.Append(LoggerCompliance.GetLogXML());
                StringBuilder.Append("</ComplianceLog>\r\n");
            }

            // Export the tags of the Data Source Record collection as XML elements.
            StringBuilder.Append(Utilities.XML.GetElement(tagObservationName, ObservationName) + "\r\n");
            StringBuilder.Append(Utilities.XML.GetElement(tagTimeCreate, TimeCreate) + "\r\n");
            StringBuilder.Append(Utilities.XML.GetElement(tagTimeStart, TimeStart) + "\r\n");
            StringBuilder.Append(Utilities.XML.GetElement(tagTriggerMethodID, TriggerMethodID) + "\r\n");

            if (TimeTriggered != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagTimeTriggered, (DateTime)TimeTriggered) + "\r\n");

            if (ChannelTriggerIdx != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagChannelTriggerIdx, ChannelTriggerIdx, null) + "\r\n");

            if (ObservationSerial!= null)
                StringBuilder.Append(Utilities.XML.GetElement(tagObservationSerial, (uint)ObservationSerial) + "\r\n");

            if (ObservationAggregationSerial != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagObservationAggregationSerial, (uint)ObservationAggregationSerial) + "\r\n");

            StringBuilder.Append("<tagChannelInstances>\r\n");
            foreach (OneChannelInst ThisChannelInst in ChannelInstances)
                StringBuilder.Append(ThisChannelInst.GetXML(ApplicationLog, ComplianceLog, MaxSeriesValues));
            StringBuilder.Append("</tagChannelInstances>\r\n");

            StringBuilder.Append(Utilities.XML.GetElement(tagComments, Comments) + "\r\n");

            if (CharactDisturbDirection != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagCharactDisturbDirection, (uint)CharactDisturbDirection) + "\r\n");

            if (CharactDisturbDirectionQuality != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagCharactDisturbDirectionQuality, (uint)CharactDisturbDirectionQuality) + "\r\n");

            if (CharactDuration != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagCharactDuration, (double)CharactDuration) + "\r\n");

            if (CharactMinVoltagePU != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagCharactMinVoltagePU, (double)CharactMinVoltagePU) + "\r\n");

            if (CharactMaxVoltagePU != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagCharactMaxVoltagePU, (double)CharactMaxVoltagePU) + "\r\n");

            if (CharactMinVoltage != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagCharactMinVoltage, (double)CharactMinVoltage) + "\r\n");

            if (CharactMaxVoltage != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagCharactMaxVoltage, (double)CharactMaxVoltage) + "\r\n");

            if (CharactMinCurrent != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagCharactMinCurrent, (double)CharactMinCurrent) + "\r\n");

            if (CharactMaxCurrent != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagCharactMaxCurrent, (double)CharactMaxCurrent) + "\r\n");

            if (SagTypeID != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagCharactMinCurrent, SagTypeID) + "\r\n");

            if (LSTtoLocal != null)
                StringBuilder.Append(Utilities.XML.GetElement(tagLSTtoLocal, LSTtoLocal) + "\r\n");            

            // Finish the Data Source Record.
            StringBuilder.Append("</tagRecObservation>\r\n");

            // Return the XML version of the Data Source Record
            return StringBuilder.ToString();

        } // GetXML      

    } // class RecObservation

} // namespace PQDIF.Validator